### ISSUE TITLE
[FEATURE] Adding features to items with spells

### ISSUE THREAD

**Issue by GhostwheelX** [morepurplemorebetter/fvtt-items-with-spells-5e#1]
There are quite a few items that have "nested" effects that don't particularly fit as spells. While they _could_ be made to be spells, it doesn't work perfectly.

Some examples of such an item include the Staff of Striking, Staff of Withering, Dagger of Venom, and the Helm of Brilliance (for the diamond and fire opal effects).

With that in mind, would it be possible to add features to the items that can be "nested" through the module, rather than keeping it restricted to just spells?

**Comment by morepurplemorebetter** [comment]
This is explicitly something that is beyond the Items with **Spells** module. This module is intended for spells, and spells only. What you are looking for is covered by the [Magic Items](https://github.com/PwQt/magic-items-2) module and will not be added to this module.

Let me quote from the readme:
> The scope of this module is intentionally limited and will not fully replace the edge-cases that [Magic Items](https://github.com/PwQt/magic-items-2) attempts to accommodate.

I'm sorry, but if you want this functionality, you'll either have to use another module or make a copy of this module and code it yourself.
