### ISSUE TITLE
[FEATURE] 3.2.0 support?

### ISSUE THREAD

**Issue by Stormthirst** [morepurplemorebetter/fvtt-items-with-spells-5e#2]
Just wondering if this awesome module was going to be updated to work with D&D 3.2.0?

Thanks

**Comment by morepurplemorebetter** [comment]
I fully intend to update this module to DnD5e v3.2 and Foundry v12. However, that will take time and please don't ask me for an ETA. I'll work on it when I can.

First up is Token Action HUD integration.

**Comment by Stormthirst** [comment]
Thanks for you hard work! Look forward to the updates.

**Comment by morepurplemorebetter** [comment]
You don't have to close this issue, I'll close issues when support is actually added.
By leaving issues open, people will see that it is being worked on and won't be inclined to open another issue.

**Comment by morepurplemorebetter** [comment]
Fixed in [v12.0.0](../releases/tag/v12.0.0).
