### ISSUE TITLE
Weapons with Spells not consuming charges on attack

### ISSUE THREAD

**Issue by Jacob-McCurdy** [morepurplemorebetter/fvtt-items-with-spells-5e#4]
Was curious if there would be a potential future update that prevented attacks consuming charges if you re using items with spells on a weapon, as it is very common for quarterstaffs to have spells. 

Would also allow the ease of creating other weapons with various spells/features that are charge based built in. 

That or just knowing if this would not be possible, or is not going to be looked into!

**Comment by morepurplemorebetter** [comment]
This is not something you need the Items with Spells module to do for you. If you uncheck `uses prompt` on the item, it will not consume a charge when you use it. The charges will then only be used when a spell linked to it is cast.

**Comment by Jacob-McCurdy** [comment]
I am a buffoon and thank you!
