### ISSUE TITLE
[BUG] dnd5e 3.3 compatibility

### ISSUE THREAD

**Issue by AlexisArcs** [morepurplemorebetter/fvtt-items-with-spells-5e#5]
## Describe the bug
The module won't load with the latest 3.3 version of the D&D 5E system

## Versions
- Items with Spells: v12.0.1
- System: dnd5e v3.3.0 or v3.3.1
- Foundry VTT: v12.328

**Comment by mattwong-dot** [comment]
Seconding this, the module will repeatedly un-load itself from the active modules list upon loading the World on each attempt. 

**Versions:**
Items with Spells: v12.0.1
System: dnd5e v3.3.1
Foundry VTT: v12.328 (V12 Stable)

**Comment by morepurplemorebetter** [comment]
I will look into this when I'm back from my holiday in two weeks. Until that time, you can edit the module.json to remove the maximum system compatibility. There is a good chance that this module will work for dnd5e v3.3.x without issue, but I simply haven't had the time to test it yet (I'm still on v3.1 in my own world).

**Comment by ItaloBorrelli** [comment]
Haven't found any issues with that. Can use my module.json in the fork and release I created. Just until @morepurplemorebetter is back if anyone needs that:
https://github.com/ItaloBorrelli/fvtt-items-with-spells-5e/releases/download/v12.0.2/module.json

**Comment by morepurplemorebetter** [comment]
Fixed in [v12.1.0](https://github.com/morepurplemorebetter/fvtt-items-with-spells-5e/releases/tag/v12.1.0).
